"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# .envファイルの読み込み
load_dotenv()

# 環境変数ファイルの読み込み
# 開発環境: development.env
# 本番環境: production.env
if os.getenv("DJANGO_ENV") == "production":
    env_path = ".env_files/production.env"
else:
    # デフォルトは開発環境
    env_path = ".env_files/development.env"
load_dotenv(dotenv_path=env_path)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8icgv5+zx!p=eqopt=)3oz$r)84c5(r=7!(rr=v=gm)7um^ei6'

# デバッグモードの設定
# 開発環境でもデフォルトはFalse（より安全な設定）
DEBUG = True

ALLOWED_HOSTS = ['*']

# メールバックエンドの設定
# DEBUG=True: コンソールに出力
# DEBUG=False: 実際にメール送信
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# allauth for mail
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# メール認証

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0").split(",")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # allauthに必要
    'allauth',
    'allauth.account',
    'app.apps.AppConfig',
]

# allauth for site
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'app', 'templates'),  # アプリケーションのテンプレート
            os.path.join(BASE_DIR, 'account', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'sakumonkun'),  # デフォルト値を指定
        'USER': os.getenv('DB_USER', 'admin'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'sakumonkun'),
        'HOST': os.getenv('DB_HOST', 'hackathonb-rds.cpsgkskiwi3a.ap-northeast-1.rds.amazonaws.com'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',  # 文字化け防止のための設定
        },
    }
}


"""
AllAuth関連
AllAuthのユーザーモデルを既存のUserモデルと紐付け
email, usernameどちらでもログイン可能にする
"""

AUTH_USER_MODEL = "app.User"

# 認証バックエンドの設定
# メールアドレスとユーザー名の両方で認証を可能にする
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# allauth の基本設定
ACCOUNT_LOGIN_METHODS = {'email'}  # emailでログイン
ACCOUNT_USERNAME_REQUIRED = True  # ユーザー名必須
ACCOUNT_EMAIL_REQUIRED = True  # メールアドレスも必須
ACCOUNT_EMAIL_VERIFICATION = 'none'  # メール確認をスキップ
ACCOUNT_UNIQUE_EMAIL = True  # メールアドレスの重複を禁止
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # メール認証を必須にする


# テンプレート設定
ACCOUNT_TEMPLATE_EXTENSION = 'html'
ACCOUNT_TEMPLATE_DIR = 'account'

# リダイレクト設定
LOGIN_URL = 'accounts:account_login'  # 名前空間を追加
LOGIN_REDIRECT_URL = 'app:home'  # ログイン後のリダイレクト先
ACCOUNT_LOGOUT_REDIRECT_URL = 'accounts:account_login'  # 名前空間を追加


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# パスワードハッシャーの設定
# 上から順に実行する。新規サービスのためハッシュ化の方針は1つでいいが、
# 実際のシステムではハッシュ化の方針を変える場合は、優先したい方式を上位に記述する。
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',  # Argon2（デフォルトはid）
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
