# Generated by Django 4.1.7 on 2025-01-29 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=200, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=200, verbose_name='パスワード')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
            ],
        ),
    ]
