# Generated by Django 4.1.7 on 2025-02-12 01:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_choiceid', models.IntegerField(verbose_name='正解の選択肢')),
                ('text', models.CharField(max_length=20, verbose_name='問題文')),
                ('explanation', models.CharField(max_length=20, verbose_name='解説')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=128, verbose_name='パスワード')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='問題タイトル')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.PROTECT, to='app.user', verbose_name='ユーザーID')),
            ],
            options={
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=20, verbose_name='選択肢文')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('questionid', models.ForeignKey(db_column='questionid', on_delete=django.db.models.deletion.PROTECT, to='app.question', verbose_name='問題ID')),
            ],
            options={
                'db_table': 'question_choices',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='testid',
            field=models.ForeignKey(db_column='testid', on_delete=django.db.models.deletion.PROTECT, to='app.test', verbose_name='テストID'),
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guestname', models.CharField(max_length=20, verbose_name='ゲスト名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('testid', models.ForeignKey(db_column='testid', on_delete=django.db.models.deletion.PROTECT, to='app.test', verbose_name='テストID')),
            ],
            options={
                'db_table': 'examinations',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_choiceid', models.IntegerField(verbose_name='選択肢')),
                ('iscorrect', models.BooleanField(default=False, verbose_name='正解')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='回答日時')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('examinationid', models.ForeignKey(db_column='examinationid', on_delete=django.db.models.deletion.CASCADE, to='app.examination', verbose_name='受験ID')),
                ('questionid', models.ForeignKey(db_column='questionid', on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name='質問ID')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
    ]
