# Generated by Django 4.1.7 on 2025-02-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='examinationid',
            field=models.ForeignKey(db_column='examinationid', on_delete=django.db.models.deletion.PROTECT, to='app.examination', verbose_name='受験ID'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='questionid',
            field=models.ForeignKey(db_column='questionid', on_delete=django.db.models.deletion.PROTECT, to='app.question', verbose_name='質問ID'),
        ),
    ]
