# Generated by Django 4.1.7 on 2025-02-17 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.user', verbose_name='ユーザーID'),
        ),
    ]
