# Generated by Django 4.1.7 on 2025-02-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_answer_examinationid_alter_answer_questionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questionid',
            field=models.ForeignKey(db_column='questionid', on_delete=django.db.models.deletion.PROTECT, to='app.question', verbose_name='問題ID'),
        ),
    ]
