# Generated by Django 4.1.7 on 2025-02-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_test_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='testid',
            field=models.ForeignKey(db_column='testid', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='app.test', verbose_name='テストID'),
        ),
    ]
