# Generated by Django 4.1.7 on 2025-02-14 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_answer_questionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answered_at',
        ),
        migrations.AddField(
            model_name='examination',
            name='answered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='回答日時'),
        ),
    ]
