# Generated by Django 4.1.7 on 2025-02-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_question_testid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='解説'),
        ),
    ]
